version: '2.0'

services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
      - tempo

  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.39.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage

  tempo:
    image: grafana/tempo:1.5.0
    command:
      [
        "--target=all",
        "--storage.trace.backend=local",
        "--storage.trace.local.path=/var/tempo",
        "--auth.enabled=false",
        "--search.enabled=true"
      ]
    # ports:
    #   - "14250:14250"
    #   - "4317:4317"

  grafana:
    image: grafana/grafana:9.1.7
    # network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning/datasources
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

volumes:
  db_postgres_data:
