version: '2.0'

services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
      - tempo

  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.39.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage

  tempo:
    image: grafana/tempo:1.5.0
    command:
      [
        "--target=all",
        "--storage.trace.backend=local",
        "--storage.trace.local.path=/var/tempo",
        "--auth.enabled=false",
        "--search.enabled=true"
      ]
    # ports:
    #   - "14250:14250"
    #   - "4317:4317"

  grafana:
    image: grafana/grafana:9.1.7
    # network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning/datasources
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

  # TODO: This would export everything to Grafana cloud, but we are using the OTEL-Collector export for now.
  # agent:
  #   image: grafana/agent:latest
  #   volumes:
  #     - ./agent/config:/etc/agent-config
  #   entrypoint:
  #     - /bin/agent
  #     - -config.file=/etc/agent-config/agent.yaml
  #     - -metrics.wal-directory=/tmp/agent/wal
  #     - -enable-features=integrations-next
  #     - -config.expand-env
  #     - -config.enable-read-api
  #   environment:
  #     HOSTNAME: agent
  #     REMOTE_WRITE_HOST: cortex:9009
  #     LOKI_HOST: loki:3100
  #     TEMPO_HOST: tempo:4317
  #     AVALANCHE_HOST: avalanche:9001
  #     MYSQL_HOST: mysql:3306
  #     POSTGRES_HOST: postgres:5432
  #     REDIS_HOST: redis:6379
  #     DNSMASQ_HOST: dnsmasq:53
  #     MEMCACHED_HOST: memcached:11211
  #     CONSUL_HOST: consul:8500
  #     ELASTICSEARCH_HOST: elasticsearch:9200
  #     KAFKA_HOST: kafka:9093
  #     MONGODB_HOST: mongodb:27017
  #   ports:
  #     - "12345:12345"
  #   depends_on:
  #     - cortex
  #     - loki
  #     - tempo

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"

volumes:
  db_postgres_data:
