version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: caleydo/phovea_circleci_python:v2.0
    steps:
      - checkout
      - run:
          name: Update npm package to v6.4.1
          command: sudo npm i -g npm@6.4.1
      - run:
          name: Show node and npm version
          command: |
            node -v
            npm -v
      - run:
          name: Install Docker packages from docker_packages.txt
          command: |
            (!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get install -y))
      - restore_cache:
          key: deps4-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Remove npm dependencies installed from git repositories (avoid caching of old commits)
          command: |
            (grep -l '._resolved.: .\(git[^:]*\|bitbucket\):' ./node_modules/*/package.json || true) | xargs -r dirname | xargs -r rm -rf
      - save_cache:
          key: deps4-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      - run:
          name: Install npm dependencies from git repositories (always get latest commit)
          command: npm install
      - run:
          name: Show installed npm dependencies
          command: npm list --depth=0
      - restore_cache:
          key: deps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Install pip requirements
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          paths:
          - ~/venv
      - run:
          name: Force an update of pip dependencies from git repositories # not sure if this is working ?
          command: |
            . ~/venv/bin/activate
            pip install --upgrade --upgrade-strategy=only-if-needed -r requirements.txt
      - run:
          name: Build
          command: |
            . ~/venv/bin/activate
            npm run build

workflows:
  version: 2
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
