FROM python:3.10-buster

LABEL maintainer="contact@caleydo.org"
WORKDIR /phovea

# install dependencies last step such that everything before can be cached
COPY requirements*.txt docker_packages.txt docker_script*.sh _docker_data* ./
RUN (!(test -s docker_packages.txt) || (apt-get update && \
    (cat docker_packages.txt | xargs apt-get install -y))) && \
    (pip install --no-cache-dir -r requirements.txt) && \
    (pip install --no-cache-dir -r requirements_dev.txt)
RUN (!(test -s docker_script.sh) || (bash ./docker_script.sh))


CMD [ "sh", "-c", "pip install --no-cache-dir --no-deps -r requirements_workspace.txt && python -m debugpy --listen 0.0.0.0:5678 -m uvicorn tdp_core.server.main:app --app-dir /phovea/tdp_core --reload --host 0.0.0.0 --port 80"]

EXPOSE 80