version: '2.0'
services:
  db_mongo:
    ports:
      - '27017:27017'
  api:
    # Override the default server command to add a debugging process. This causes the app to run slower, therefore it is optional.
    command: 'python -m debugpy --listen 0.0.0.0:5678 -m uvicorn tdp_core.server.main:app --reload --host 0.0.0.0 --port 9000'