FROM python:3.10-buster

LABEL maintainer="contact@caleydo.org"
WORKDIR /phovea

COPY requirements*.txt ./
RUN (apt-get update) && \
    (pip install --no-cache-dir -r requirements.txt) && \
    (pip install --no-cache-dir -r requirements_dev.txt)

CMD [ "sh", "-c", "pip install --no-cache-dir --no-deps -r requirements_workspace.txt && python -m debugpy --listen 0.0.0.0:5678 -m uvicorn tdp_core.server.main:app --reload --host 0.0.0.0 --port 9000"]

EXPOSE 9000