name: Create a new release PR

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: 'The next version to release'
        required: true

jobs:
  release:
    uses: datavisyn/github-workflows/.github/workflows/release-source.yml@main
    secrets: inherit
    with:
      release_version: ${{ inputs.release_version }}